# Generated by Django 3.1.1 on 2020-11-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0003_auto_20201103_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='Image',
        ),
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='get_upload_player'),
        ),
    ]
