# Generated by Django 3.1.1 on 2020-11-04 02:57

from django.db import migrations, models
import mtg.models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0004_auto_20201103_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=mtg.models.get_upload_player),
        ),
    ]
