# Generated by Django 3.1.1 on 2020-11-05 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0005_auto_20201103_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_2', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('winner', models.CharField(blank=True, max_length=40)),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtg.player')),
            ],
        ),
    ]
