# Generated by Django 3.1.1 on 2020-11-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0006_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(default='ongoing', max_length=40),
        ),
    ]
