# Generated by Django 3.1.1 on 2020-11-07 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0007_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Jugador_1', to='mtg.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Jugador_2', to='mtg.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ongoing'), (2, 'Cancelled'), (3, 'Finished')], default='ongoing'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.CharField(max_length=40),
        ),
    ]
