# Generated by Django 3.1.1 on 2020-11-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0009_auto_20201107_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status_2',
            field=models.CharField(choices=[('OG', 'ongoing'), ('CA', 'cancelled'), ('FI', 'finished')], default='ongiong', max_length=40),
        ),
    ]
