# Generated by Django 3.1.1 on 2020-11-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0010_match_status_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='status',
        ),
        migrations.AlterField(
            model_name='match',
            name='status_2',
            field=models.CharField(choices=[('ongoing', 'ongoing'), ('cancelled', 'cancelled'), ('finished', 'finished')], default='ongiong', max_length=40),
        ),
    ]
